/nav/tree_exec:
  ros__parameters:
    log_level: "info"
    tick_period_milliseconds: 100
    enable_bt_monitor: true
    bt_snapshot_topic: "bt_snapshot"

    game_info_topic_name: "game_info"
    odom_topic: "/odom"
    sentry_cmd_topic: "sentry_cmd"
    use_spin_topic: "/nav/use_spin"
    # empty = share/rm_decision_cpp/config/zones.yaml
    zones_yaml: ""
