uint16 current_hp
uint8 game_progress
uint16 game_remaining_time
uint8 remaining_energy
uint16 ally_outpost_hp
uint16 ally_base_hp
uint8 hurt_hp_deduction_reason
uint8 posture
bool out_of_combat
uint16 redeemable_17mm
uint16 bullet_remaining_17mm
bool energy_activatable

uint16 coin_remaining
uint16 enemy_outpost_hp
uint16 enemy_base_hp
uint16 current_heat
uint16 heat_limit
# 0=inactive 1=active
uint8 big_energy_status
# 0=auto 1=manual
uint8 control_mode
float32 manual_goal_x
float32 manual_goal_y
bool can_free_resurrect
